baseURL = "/"
languageCode = "en-gb"
title = "Bethan Evans"
theme = "spectrum"

[params]
subtitle = "Workshops"
email = "bethan@techniqueforlife.com"

[[menus.main]]
url = "/"
name = "Home"
weight = 1

[[menus.main]]
url = "/workshops"
name = "Workshops"
weight = 2

#[[menus.main]]
#url = "/calendar"
#name = "Calendar"
#weight = 3

#[[menus.main]]
#url = "/about"
#name = "About"
#weight = 4


